// <auto-generated />
using System;
using ControleEpi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleEpi.Migrations
{
    [DbContext(typeof(AppdbContext))]
    [Migration("20241014061946_CreateDbEpiColaboradorList")]
    partial class CreateDbEpiColaboradorList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ControleEpi.Model.Colaborador", b =>
                {
                    b.Property<int>("ColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ColaboradorId"));

                    b.Property<string>("ColaboradorNome")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataDemissao")
                        .HasColumnType("date");

                    b.HasKey("ColaboradorId");

                    b.ToTable("colaboradors");
                });

            modelBuilder.Entity("ControleEpi.Model.Epi", b =>
                {
                    b.Property<int>("EpiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EpiId"));

                    b.Property<string>("EpiDescricao")
                        .HasColumnType("longtext");

                    b.Property<string>("EpiName")
                        .HasColumnType("longtext");

                    b.Property<int>("EpiValidade")
                        .HasColumnType("int");

                    b.HasKey("EpiId");

                    b.ToTable("epis");
                });

            modelBuilder.Entity("ControleEpi.Model.ListaEpi", b =>
                {
                    b.Property<int>("ListaEpiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ListaEpiId"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<int>("EpiId")
                        .HasColumnType("int");

                    b.HasKey("ListaEpiId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("EpiId");

                    b.ToTable("ListaEpi");
                });

            modelBuilder.Entity("ControleEpi.Model.ListaEpi", b =>
                {
                    b.HasOne("ControleEpi.Model.Colaborador", "colaborador")
                        .WithMany("listaEpis")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleEpi.Model.Epi", "Epi")
                        .WithMany("listaEpis")
                        .HasForeignKey("EpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epi");

                    b.Navigation("colaborador");
                });

            modelBuilder.Entity("ControleEpi.Model.Colaborador", b =>
                {
                    b.Navigation("listaEpis");
                });

            modelBuilder.Entity("ControleEpi.Model.Epi", b =>
                {
                    b.Navigation("listaEpis");
                });
#pragma warning restore 612, 618
        }
    }
}
